book store/Models/Chart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace book_store.Models
{
    public class Chart
    {
        public Chart(string adress, string title, string small, int ariaValuenow, int ariaValuemin, int ariaValuemax, string span)
        {
            Adress = adress;
            Title = title;
            Small = small;
            AriaValuenow = ariaValuenow;
            AriaValuemin = ariaValuemin;
            AriaValuemax = ariaValuemax;
            Span = span;
        }

        public string Adress{ get; set; }
        public string Title{ get; set; }
        public string Small{ get; set; }
        public int AriaValuenow { get; set; }
        public int AriaValuemin { get; set; }
        public int AriaValuemax { get; set; }
        public  string Span{ get; set; }
       
    }
}

book store/Models/Contact.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace book_store.Models
{
    public class Contact
    {
      
        [Required(ErrorMessage = "پر کردن این فیلد اجباری هست")]
        public string Name { get; set; }
        public string LastName { get; set; }
        [Required(ErrorMessage = "پر کردن این فیلد اجباری هست")]
        public string Massage { get; set; }
        [Required(ErrorMessage = "پر کردن این فیلد اجباری هست")]
        [EmailAddress(ErrorMessage ="مقدار وارد شده صحیح نمیباشد")]
        public string Email{ get; set; }
        public int phone { get; set; }

    }
}

book store/Models/ErrorViewModel.cs
using System;

namespace book_store.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

book store/Models/Portfolio.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace book_store.Models
{
    public class Portfolio
    {
        public Portfolio(string title)
        {
            Title = title;
          
        }

        public String Title { get; set; }
     
    }
}

book store/Controllers/HomeController.cs
using book_store.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace book_store.Controllers
{
    public class HomeController : Controller
    {

        
        
        public IActionResult Index()

        {

            return View();
        }
     
        //public IActionResult Portfolio()
        //{
        //    return View();
        //}
        //public IActionResult Experience()
        //{

        //    return View();
        //}
        //public IActionResult Client()
        //{

        //    return View();
        //}
        [HttpGet]
        public IActionResult Contact()
        {

            var model = new Contact();
            return View(model);
        }
        [HttpPost]
        public PartialViewResult Contact(Contact form)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.error = "اعطلاعات وارد شده صحیح نمیباشد";
                return PartialView(form);
            }
            ViewBag.success = "پیام شما با موفقیت ارسال شد";
            ModelState.Clear();
            return PartialView();
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

book store/ViewComponent/ChartsViewComponent.cs
using book_store.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace book_store
{
    public class ChartsViewComponent :ViewComponent
    {
       

        public IViewComponentResult Invoke()
        {
            var chart = new List<Chart>
            {
               new Chart(" https://modireforosh.ir/best-science-books/","کتاب های علمی","90%",90,0,90,"90% Complete"),
               new Chart("https://www.fadakbook.ir/","کتاب های دانشگاهی","100%",100,0,100,"100% Complete"),
               new Chart("https://www.gajmarket.com","کتاب های درسی و کنکوری","85%",85,0,85,"85% Complete"),
               new Chart("https://jangal.com/","کتاب های خارجی","60%",60,0,60,"60% Complete"),
               new Chart("https://www.banasher.com/","کتاب داستان و رمان ها","70%",70,0,70,"70% Complete")

            };
            return View("_charts",chart);

        }
    }
   
}

book store/Views/Home/Components/Charts/_charts.cshtml
@model IEnumerable<book_store.Models.Chart>

@{

    ViewData["Title"] = "انواع کتاب";
}
<h1 class="title">درباره ما</h1>

<div class="col-md-12 col-sm-12 col-xs-12  omega  about">
    <p align="center" class="about_info">
        نريال یک فروشگاه زنجیره‌ای است و شاید بتوان آن را تنها فروشگاه زنجیره‌ای کتاب کشور و یکی از بهترین کتاب فروشی های تهران نامید. این مجموعه بزرگ دارای ۴۰ شعبه، تنها در شهر تهران، است و شما می‌توانید در آن هر محصول فرهنگی، از کتاب‌های مختلف در رده‌های سنی گوناگون گرفته تا لوازم‌التحریر و هدایای نفیس دیگر بیابید. اگر به دنبال کتاب‌های زبان اصلی می‌گردید، نريال یکی از گزینه‌های خوب برای این کار است

        تمامی شعبه‌های شهر کتاب در تهران جذاب و دنج هستند، اما شهر کتاب‌های فرشته و الهیه از سوی کتاب‌خوان‌ها بیشتر به همه توصیه می‌شوند. همچنین نريال مرکزی بیشتر از سایر شعبه‌ها شناخته‌شده است.

    </p>
   

</div>
@foreach (var chart in Model)
{
    <div class="rzm_progress_bar">
        <a href=@chart.Adress><h4>@chart.Title</h4></a>
        <small class="pull-right rzm_perchantage">@chart.Small</small>
        <div class="progress">
            <div class="progress-bar" role="progressbar" aria-valuenow="@chart.AriaValuenow" aria-valuemin="@chart.AriaValuemin" aria-valuemax="@chart.AriaValuemax" style="width:7%;">
                <span class="sr-only">@chart.Span</span>
            </div>
        </div>
    </div>
}
<p align="right">با کلیک  کردن روی عنوان کتاب به سایت آن وارد می شوید </p>

book store/Views/Shared/About.cshtml
<div class="col-md-3 col-sm-12 rzm_profile_nav">
    <div class="sticky">
        <div class="logo">
            <img src="img\profile_photo1.jpg" alt="profile_photo" class="img-responsive img-circle">
        </div>
        <div class="rzm_main_menu hidden-sm hidden-xs">

            <div class="rzm_main_menu hidden-sm hidden-xs">
            <ul class="primary">

                    <li class="first"><a href="#home">درباره ما </a></li>
                    <li><a href="#portfolio">کتاب های ما</a></li>
                    <li><a href="#experience">تاریخچه ما</a></li>
                    @*<li><a href="#client">Clients</a></li>*@
                    <li><a href="#testimonial">افراد موفق</a></li>
                    <li><a class="contact-form" href="#contact">نظرات شما</a></li>
                    <li><a href="#home" class="go_to_top">Top <i class="fa fa-arrow-up" aria-hidden="true"></i></a></li>
                </ul>

        </div>
            <div class="social_nav">
                <a href=""><i class="fa fa-facebook" aria-hidden="true"></i></a>
                <a href=""><i class="fa fa-twitter" aria-hidden="true"></i></a>
                <a href=""><i class="fa fa-behance" aria-hidden="true"></i></a>
                <a href=""><i class="fa fa-dribbble" aria-hidden="true"></i></a>
            </div>
        </div>
    </div>
</div>

<div class="clearfix"></div>
<section class="col-md-9 col-sm-12 col-xs-12 col-md-offset-3 first profile rez_about">
    <div class="rez_top_title">
        <h1 align="center">ما فقط کتاب میفروشیم</h1>
        <p align="center">به فروشگاه نريال خوش امدید</p>
        <p style="font-size:16px;" align="right">   .خواندن به شما شعف، آگاهی، شوق و توانایی می‌بخشد؛ عاقل آن را تمنا می‌کند، تهی‌مابه از آن می‌گذرد و نادان آن را نادیده می‌گیرد  </p>
        <p style="font-size:16px;" align="right">. کتاب ها ذهن شما را هوشیار می‌کنند. آن‌ها آرامش، حقیقت، تعادل،آزادی، اعتماد به نفس و شوری بیکران به زندگی شما می‌بخشند</p>
        <p style="font-size:18px;" align="right">داستایوفسکی</p>

    </div>
    @await Component.InvokeAsync("Charts")

<div class="clear">
    </div>

</section>

book store/Views/Shared/Menu.cshtml
<div class="rzm_mobile_header col-sm-12 col-xs-12 hidden-lg hidden-md">
        <div class="mob_nav  navbar navbar-inverse navbar-fixed-top" id="slide-nav">
            <div class="navbar-header">
                <a class="navbar-toggle"></a>
            </div>
            <div id="slidemenu" class="navbar-default navbar-inverse">
                <ul class="nav navbar-nav primary">

                    <li><a href="@Url.Action("About","Shared")"> درباره ما</a></li>
                    <li><a href="">کتاب ها ما</a></li>
                    <li><a href="@Url.Action("Experience","Home")">تاریخچه ما</a></li>
                    <li><a href="#client">Clients</a></li>
                    <li><a href="#@Url.Action("Testimonial","Home")">افراد موفق</a></li>
                    <li><a class="contact-form" href="@Url.Action("Contact","Home")">نظرات شما</a></li>

                </ul>
            </div>
        </div>
    </div>
<div class="rzm_outside-header" id="home">
</div>

 

book store/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">


<head>

    <!-- Basic Page Needs
      ================================================== -->
    <meta charset="utf-8">
    <title>فروشگاه بزرگ کتاب نريال</title>
    <meta name="description" content="">
    <meta name="author" content="">

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!-- CSS
      ================================================== -->

    <link rel="stylesheet" href="stylesheets/animate.css">
    <link rel="stylesheet" href="stylesheets/layout.css">
    <link rel="stylesheet" href="stylesheets/responsive.css">
    <link rel="stylesheet" href="bootstrap/css/bootstrap.min.css">

    <link rel="stylesheet" type="text/css" href="image_gallery/css/jquery.fancybox.css">
    <link rel="stylesheet" href="image_gallery/css/styles.css">

    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

    <script src="bootstrap/js/bootstrap.min.js"></script>


    <link rel="shortcut icon" href="img/favicon1.png">



</head>
<body>
    @RenderBody()



   
        @*================================================== -->*@

    <script src="javascripts/jquery.tipsy.js"></script>

    <script src="javascripts/jquery.scrollTo-min.js"></script>
    <script src="javascripts/jquery.localscroll-min.js"></script>
    <script src="javascripts/jquery.easing.1.3.js"></script>
    <script src="javascripts/script.js"></script>

    <!--contact form script starts-->
    <script src="contact.js"></script>
    <script src="javascripts/jquery.validate.js" type="text/javascript"></script>

    <script src="image_gallery/js/isotope.min.js"></script>
    <script src="image_gallery/js/jquery.fancybox.pack.js"></script>
    <script src="image_gallery/js/main.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>



    <!-- End Document
    ================================================== -->
</body>


</html>